--
-- VHDL Architecture filters.highpass_50.struct_simplified_bq1
--
-- Created:
--          by - fas.UNKNOWN (WE3866)
--          at - 15:31:59 09.08.2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
   USE ieee.std_logic_1164.all;
   USE ieee.numeric_std.all;

LIBRARY filters;

ARCHITECTURE struct_simplified_bq1 OF highpass_50 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL sample_out_biquad_1_s : signed((data_size_g -1) DOWNTO 0);
   SIGNAL sample_out_biquad_2_s : signed((data_size_g -1) DOWNTO 0);


   -- Component Declarations
   COMPONENT amplifier_2
   GENERIC (
      data_size_g : positive := 16
   );
   PORT (
      clock_i : IN     std_ulogic ;
      reset_i : IN     std_ulogic ;
      u_i     : IN     signed ((data_size_g -1) DOWNTO 0);
      y_o     : OUT    signed ((data_size_g -1) DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT biquad_1
   GENERIC (
      data_size_g : positive := 16
   );
   PORT (
      clock_i  : IN     std_ulogic ;
      enable_i : IN     std_ulogic ;
      reset_i  : IN     std_ulogic ;
      u_i      : IN     signed ((data_size_g -1) DOWNTO 0);
      y_o      : OUT    signed ((data_size_g -1) DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT biquad_2
   GENERIC (
      data_size_g : positive := 16
   );
   PORT (
      clock_i  : IN     std_ulogic ;
      enable_i : IN     std_ulogic ;
      reset_i  : IN     std_ulogic ;
      u_i      : IN     signed ((data_size_g -1) DOWNTO 0);
      y_o      : OUT    signed ((data_size_g -1) DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : amplifier_2 USE ENTITY filters.amplifier_2;
   FOR ALL : biquad_1 USE ENTITY filters.biquad_1;
   FOR ALL : biquad_2 USE ENTITY filters.biquad_2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I3 : amplifier_2
      GENERIC MAP (
         data_size_g => data_size_g
      )
      PORT MAP (
         clock_i => clock_i,
         reset_i => reset_i,
         u_i     => sample_out_biquad_2_s,
         y_o     => sample_o
      );
   I0 : biquad_1
      GENERIC MAP (
         data_size_g => data_size_g
      )
      PORT MAP (
         clock_i  => clock_i,
         enable_i => enable_i,
         reset_i  => reset_i,
         u_i      => sample_i,
         y_o      => sample_out_biquad_1_s
      );
   I1 : biquad_2
      GENERIC MAP (
         data_size_g => data_size_g
      )
      PORT MAP (
         clock_i  => clock_i,
         enable_i => enable_i,
         reset_i  => reset_i,
         u_i      => sample_out_biquad_1_s,
         y_o      => sample_out_biquad_2_s
      );

END struct_simplified_bq1;
